@base = http://localhost:8000

# post
POST {{base}}/inscripcion/
Content-Type: application/json

{
    "nombre":"lucio",
    "apellido":"petrucci",
    "dni":11110000,
    "stage": 1,
    "nacimiento":"2002-08-11",
    "genero":"m"
}

###

GET {{base}}